### ISSUE TITLE
basic 7 have same questiong

### ISSUE THREAD

**Issue by 1JayPeng** [attilathedud/HellboundHackers#1]
now this is challenge/basic web hacking 3 . 

and When I modify the cookies as you said, it prompts to let me enter the password "Sorry But you need to submit the password."

why?

**Comment by attilathedud** [comment]
Sorry, been a long time since I looked at this challenge, so going off my memory here. I believe you need to change the username and password cookies to their binary form, and then supply the binary form of sam to the username field. The challenge is really weird.
